const presets = [
  { id:'auth', icon:'⌁', title:'SSH и авторизация', text:'sshd_config, ключи, sudoers и события входа', rules:[['/etc/ssh/sshd_config','wa','ssh_config'],['/etc/ssh/sshd_config.d','wa','ssh_config'],['/etc/sudoers','wa','sudoers'],['/etc/sudoers.d','wa','sudoers'],['/var/log/auth.log','wa','auth_log']] },
  { id:'identity', icon:'◉', title:'Учётные записи', text:'Пользователи, группы, пароли и shadow', rules:[['/etc/passwd','wa','identity'],['/etc/group','wa','identity'],['/etc/shadow','wa','identity'],['/etc/gshadow','wa','identity'],['/etc/security/opasswd','wa','identity']] },
  { id:'system', icon:'⚙', title:'Система и службы', text:'systemd, загрузчик, модули и hostname', rules:[['/etc/systemd/system','wa','systemd'],['/usr/lib/systemd/system','wa','systemd'],['/etc/hostname','wa','system_config'],['/etc/hosts','wa','system_config'],['/etc/modprobe.d','wa','kernel_modules']] },
  { id:'schedule', icon:'◷', title:'Cron и задачи', text:'Планировщики cron, at и системные таймеры', rules:[['/etc/crontab','wa','cron'],['/etc/cron.d','wa','cron'],['/etc/cron.daily','wa','cron'],['/var/spool/cron','wa','cron'],['/etc/at.allow','wa','at_jobs']] },
  { id:'network', icon:'↔', title:'Сеть', text:'Конфигурация интерфейсов, DNS и firewall', rules:[['/etc/hosts','wa','network_config'],['/etc/resolv.conf','wa','network_config'],['/etc/network','wa','network_config'],['/etc/NetworkManager','wa','network_config'],['/etc/nftables.conf','wa','firewall']] },
  { id:'privilege', icon:'◆', title:'Привилегии', text:'Бинарные файлы, suid/sgid и sudo', rules:[['/usr/bin/sudo','x','privileged'],['/usr/bin/su','x','privileged'],['/bin/su','x','privileged'],['/etc/sudo.conf','wa','sudoers']] },
  { id:'logs', icon:'▤', title:'Логи auditd', text:'Настройки демона и сохранность журналов', rules:[['/etc/audit/auditd.conf','wa','audit_config'],['/etc/audit/rules.d','wa','audit_rules'],['/var/log/audit','wa','audit_log']] },
  { id:'containers', icon:'□', title:'Контейнеры', text:'Docker и container runtime конфигурация', rules:[['/etc/docker','wa','docker'],['/etc/containerd','wa','containerd'],['/etc/containers','wa','containers']] },
  { id:'pam', icon:'⊞', title:'PAM и security policy', text:'Политики доступа, лимиты и PAM-модули', rules:[['/etc/pam.d','wa','pam'],['/etc/security','wa','security_policy'],['/etc/login.defs','wa','login_policy'],['/etc/libuser.conf','wa','identity_policy']] },
  { id:'packages', icon:'▣', title:'Пакеты и обновления', text:'APT, DNF, YUM и история установки ПО', rules:[['/etc/apt','wa','package_manager'],['/etc/yum.conf','wa','package_manager'],['/etc/dnf','wa','package_manager'],['/var/log/apt','wa','package_manager'],['/var/log/dnf.log','wa','package_manager']] },
  { id:'certificates', icon:'◇', title:'Сертификаты и ключи', text:'TLS-сертификаты, CA и закрытые ключи', rules:[['/etc/ssl','wa','certificates'],['/etc/pki','wa','certificates'],['/etc/letsencrypt','wa','certificates'],['/root/.ssh','wa','root_ssh_keys']] },
  { id:'web', icon:'◫', title:'Веб-серверы', text:'Nginx, Apache и конфигурация сайтов', rules:[['/etc/nginx','wa','nginx'],['/etc/apache2','wa','apache'],['/etc/httpd','wa','apache'],['/var/www','wa','web_content']] },
  { id:'databases', icon:'◈', title:'Базы данных', text:'Конфигурация PostgreSQL, MySQL и Redis', rules:[['/etc/postgresql','wa','postgresql'],['/etc/mysql','wa','mysql'],['/etc/my.cnf','wa','mysql'],['/etc/redis','wa','redis']] },
  { id:'backup', icon:'◰', title:'Резервные копии', text:'Настройки Borg, Restic, rsnapshot и бэкапов', rules:[['/etc/borgmatic','wa','backup'],['/etc/restic','wa','backup'],['/etc/rsnapshot.conf','wa','backup'],['/etc/backup','wa','backup']] },
  { id:'boot', icon:'▲', title:'Загрузка и kernel', text:'GRUB, initramfs и параметры загрузки', rules:[['/etc/default/grub','wa','boot_config'],['/boot/grub','wa','boot_config'],['/boot/grub2','wa','boot_config'],['/etc/sysctl.conf','wa','kernel_config'],['/etc/sysctl.d','wa','kernel_config']] },
  { id:'admin', icon:'⌘', title:'Администрирование', text:'Команды управления пользователями и сетью', rules:[['/usr/sbin/useradd','x','user_management'],['/usr/sbin/userdel','x','user_management'],['/usr/sbin/usermod','x','user_management'],['/usr/bin/passwd','x','password_change'],['/usr/sbin/visudo','x','sudoers_change']] },
  { id:'usb', icon:'⊙', title:'USB и носители', text:'Монтирование носителей и udev-правила', rules:[['/etc/udev/rules.d','wa','udev_rules'],['/etc/fstab','wa','mount_config'],['/bin/mount','x','mounts'],['/bin/umount','x','mounts']] },
  { id:'virtualization', icon:'⬡', title:'Виртуализация', text:'KVM, libvirt и конфигурация виртуальных машин', rules:[['/etc/libvirt','wa','libvirt'],['/var/lib/libvirt','wa','libvirt'],['/etc/qemu','wa','qemu']] },
  { id:'mail', icon:'✉', title:'Почта и уведомления', text:'Postfix, Exim и конфигурация почтовых служб', rules:[['/etc/postfix','wa','postfix'],['/etc/exim4','wa','exim'],['/etc/aliases','wa','mail_config']] }
];
const active = new Set(); let custom = [];
const grid = document.querySelector('#preset-grid'), output = document.querySelector('#rules-output'), count = document.querySelector('#rule-count'), download = document.querySelector('#download-button');
function esc(v){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function allRules(){const rules=[...presets.filter(p=>active.has(p.id)).flatMap(p=>p.rules),...custom],seen=new Set();return rules.filter(([path,perm])=>{const id=`${path}:${perm}`;if(seen.has(id))return false;seen.add(id);return true})}
function render(){const rules=allRules(); document.querySelectorAll('.preset').forEach(el=>{const enabled=active.has(el.dataset.id);el.classList.toggle('active',enabled);el.setAttribute('aria-pressed',enabled)}); document.querySelector('#custom-list').innerHTML=custom.map((r,i)=>`<div class="custom-rule"><code>${esc(r[0])}</code><span class="permission-badge">-${esc(r[1])}</span><span class="key-badge">${esc(r[2])}</span><button class="remove" data-index="${i}" type="button" aria-label="Удалить путь ${esc(r[0])}">×</button></div>`).join(''); const content=rules.length ? `# AuditCraft — generated auditd rules\n# Review paths before deploying to production.\n\n${rules.map(([path,perm,key])=>`-w ${path} -p ${perm} -k ${key || 'auditcraft'}`).join('\n')}\n` : '# Выберите пресеты слева,\n# чтобы начать сборку правил.'; output.querySelector('code').textContent=content; count.textContent=`${rules.length} ${rules.length===1?'RULE':'RULES'}`; download.disabled=!rules.length}
presets.forEach(p=>{const el=document.createElement('button');el.type='button';el.className='preset';el.dataset.id=p.id;el.setAttribute('aria-pressed','false');el.innerHTML=`<span class="preset-title"><span class="preset-icon">${p.icon}</span><span>${p.title}</span><span class="check">✓</span></span><p>${p.text}</p>`;el.addEventListener('click',()=>{active.has(p.id)?active.delete(p.id):active.add(p.id);render()});grid.append(el)});
document.querySelector('#path-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget),path=data.get('path').trim(),perm=data.getAll('permission').join(''),key=data.get('key').trim().replace(/\s+/g,'_');if(!path)return document.querySelector('#custom-path').focus();if(!path.startsWith('/'))return alert('Укажите абсолютный путь, начинающийся с /.');if(!perm)return alert('Выберите хотя бы одно событие.');custom.push([path,perm,key||'custom_path']);e.currentTarget.reset();e.currentTarget.querySelector('[value="w"]').checked=true;e.currentTarget.querySelector('[value="a"]').checked=true;render()});
document.querySelector('#custom-list').addEventListener('click',e=>{if(e.target.matches('.remove')){custom.splice(Number(e.target.dataset.index),1);render()}});
document.querySelector('#clear-all').addEventListener('click',()=>{active.clear();custom=[];render()});
document.querySelector('#copy-button').addEventListener('click',async e=>{if(!allRules().length)return;const value=output.querySelector('code').textContent;try{await navigator.clipboard.writeText(value)}catch{const area=document.createElement('textarea');area.value=value;document.body.append(area);area.select();document.execCommand('copy');area.remove()}e.currentTarget.textContent='✓ Скопировано';setTimeout(()=>e.currentTarget.textContent='⧉ Копировать',1400)});
download.addEventListener('click',()=>{const blob=new Blob([output.querySelector('code').textContent],{type:'text/plain'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='auditcraft.rules';link.click();URL.revokeObjectURL(link.href)});document.querySelector('#year').textContent=new Date().getFullYear();render();
