const presets=[
['auth','⌁','SSH и авторизация','sshd, sudoers и события входа',[['/etc/ssh/sshd_config','wa','ssh_config'],['/etc/ssh/sshd_config.d','wa','ssh_config'],['/etc/sudoers','wa','sudoers'],['/etc/sudoers.d','wa','sudoers']]],
['identity','◉','Учётные записи','Пользователи, группы, пароли и shadow',[['/etc/passwd','wa','identity'],['/etc/group','wa','identity'],['/etc/shadow','wa','identity'],['/etc/gshadow','wa','identity']]],
['pam','⊞','PAM и security policy','PAM, лимиты и политики доступа',[['/etc/pam.d','wa','pam'],['/etc/security','wa','security_policy'],['/etc/login.defs','wa','login_policy']]],
['system','⚙','Система и службы','systemd, hostname и модули',[['/etc/systemd/system','wa','systemd'],['/usr/lib/systemd/system','wa','systemd'],['/etc/hostname','wa','system_config'],['/etc/modprobe.d','wa','kernel_modules']]],
['schedule','◷','Cron и задачи','Cron, at и фоновые задания',[['/etc/crontab','wa','cron'],['/etc/cron.d','wa','cron'],['/etc/cron.daily','wa','cron'],['/var/spool/cron','wa','cron']]],
['network','↔','Сеть и firewall','DNS, интерфейсы и фильтрация',[['/etc/hosts','wa','network_config'],['/etc/resolv.conf','wa','network_config'],['/etc/network','wa','network_config'],['/etc/nftables.conf','wa','firewall']]],
['packages','▣','Пакеты и обновления','APT, DNF, YUM и история ПО',[['/etc/apt','wa','package_manager'],['/etc/dnf','wa','package_manager'],['/etc/yum.conf','wa','package_manager'],['/var/log/apt','wa','package_manager']]],
['certificates','◇','Сертификаты и ключи','TLS, CA и ключи root SSH',[['/etc/ssl','wa','certificates'],['/etc/pki','wa','certificates'],['/etc/letsencrypt','wa','certificates'],['/root/.ssh','wa','root_ssh_keys']]],
['web','◫','Веб-серверы','Nginx, Apache и web-контент',[['/etc/nginx','wa','nginx'],['/etc/apache2','wa','apache'],['/etc/httpd','wa','apache'],['/var/www','wa','web_content']]],
['databases','◈','Базы данных','PostgreSQL, MySQL и Redis',[['/etc/postgresql','wa','postgresql'],['/etc/mysql','wa','mysql'],['/etc/my.cnf','wa','mysql'],['/etc/redis','wa','redis']]],
['containers','□','Контейнеры','Docker, containerd и Podman',[['/etc/docker','wa','docker'],['/etc/containerd','wa','containerd'],['/etc/containers','wa','containers']]],
['boot','▲','Загрузка и kernel','GRUB, sysctl и параметры ядра',[['/etc/default/grub','wa','boot_config'],['/boot/grub','wa','boot_config'],['/boot/grub2','wa','boot_config'],['/etc/sysctl.d','wa','kernel_config']]],
['admin','⌘','Администрирование','Управление пользователями и sudo',[['/usr/sbin/useradd','x','user_management'],['/usr/sbin/userdel','x','user_management'],['/usr/sbin/usermod','x','user_management'],['/usr/bin/passwd','x','password_change'],['/usr/sbin/visudo','x','sudoers_change']]],
['usb','⊙','USB и носители','Монтирование и udev-правила',[['/etc/udev/rules.d','wa','udev_rules'],['/etc/fstab','wa','mount_config'],['/bin/mount','x','mounts'],['/bin/umount','x','mounts']]],
['virtualization','⬡','Виртуализация','KVM, libvirt и QEMU',[['/etc/libvirt','wa','libvirt'],['/var/lib/libvirt','wa','libvirt'],['/etc/qemu','wa','qemu']]],
['backup','◰','Резервные копии','Borg, Restic и rsnapshot',[['/etc/borgmatic','wa','backup'],['/etc/restic','wa','backup'],['/etc/rsnapshot.conf','wa','backup']]],
['logs','▤','Auditd и журналы','Конфигурация демона и правила',[['/etc/audit/auditd.conf','wa','audit_config'],['/etc/audit/rules.d','wa','audit_rules'],['/var/log/audit','wa','audit_log']]],
['mail','✉','Почта и уведомления','Postfix, Exim и aliases',[['/etc/postfix','wa','postfix'],['/etc/exim4','wa','exim'],['/etc/aliases','wa','mail_config']]]
];
const profileMap={minimal:['auth','identity','logs'],server:['auth','identity','pam','system','schedule','network','logs'],web:['auth','identity','web','certificates','network','packages','logs'],database:['auth','identity','databases','backup','certificates','logs'],container:['auth','identity','containers','network','packages','logs'],incident:['auth','identity','pam','system','network','admin','usb','boot','logs']};
const profileNames={minimal:'Минимум',server:'Linux server',web:'Web server',database:'Database',container:'Docker host',incident:'Incident response'};
const $=s=>document.querySelector(s);const active=new Set();let custom=[];let currentTab='rules';
const grid=$('#preset-grid'),profiles=$('#profiles'),code=$('#code-output code');
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function cfg(){return {distro:$('#distro').value,destination:$('#destination').value,host:$('#log-host').value.trim(),port:$('#log-port').value.trim()||'6514',transport:$('#transport').value}}
function rules(){const seen=new Set();return [...presets.filter(p=>active.has(p[0])).flatMap(p=>p[4]),...custom].filter(r=>{const k=r[0]+'|'+r[1];if(seen.has(k))return false;seen.add(k);return true})}
function rulesText(){const out=rules();return `# AuditCraft — generated auditd rules\n# Review all paths on the target system before deployment.\n# Generated: ${new Date().toISOString().slice(0,10)}\n\n${out.length?out.map(r=>`-w ${r[0]} -p ${r[1]} -k ${r[2]}`).join('\n'):'# Select a preset in AuditCraft to generate rules.'}\n`}
function rsyslogText(){const c=cfg();if(c.destination==='local')return '# Local auditd only\n# auditd writes events to /var/log/audit/audit.log.\n# Select a remote destination in AuditCraft to generate an rsyslog forwarding snippet.\n';const target=c.host||'LOG_SERVER_HOSTNAME';const tls=c.transport==='tls';return `# /etc/rsyslog.d/60-auditcraft.conf\n# Forward auditd log records generated by AuditCraft.\nmodule(load="imfile")\n\ninput(type="imfile"\n      File="/var/log/audit/audit.log"\n      Tag="auditd:"\n      Facility="local6"\n      Severity="info"\n      PersistStateInterval="100")\n\nif ($syslogtag startswith "auditd:") then {\n  action(type="omfwd"\n         Target="${target}"\n         Port="${c.port}"\n         Protocol="tcp"${tls?'\n         StreamDriver="gtls"\n         StreamDriverMode="1"\n         StreamDriverAuthMode="x509/name"':''})\n  stop\n}\n`}
function installText(){const c=cfg(),deb=c.distro==='debian',pkg=deb?'auditd rsyslog':'audit rsyslog',restartAudit='sudo systemctl restart auditd';return `#!/usr/bin/env bash\nset -euo pipefail\n\n# 1. Install required services\nsudo ${deb?'apt-get update && apt-get install -y':'dnf install -y'} ${pkg}\n\n# 2. Install auditd rules\nsudo install -d -m 750 /etc/audit/rules.d\nsudo install -m 640 auditcraft.rules /etc/audit/rules.d/auditcraft.rules\nsudo augenrules --load\n${restartAudit}\n\n${c.destination==='local'?'# Remote forwarding is not selected.\n':`# 3. Install rsyslog forwarding configuration\nsudo install -m 640 60-auditcraft.conf /etc/rsyslog.d/60-auditcraft.conf\nsudo rsyslogd -N1\nsudo systemctl restart rsyslog\n`}# 4. Verify loaded rules\nsudo auditctl -l\n`}
function verifyText(){const r=rules(),key=r[0]?.[2]||'ssh_config';return `# Check auditd service and loaded rules\nsudo systemctl status auditd --no-pager\nsudo auditctl -l\n\n# Search events by a selected key\nsudo ausearch -k ${key} -i\n\n# Summary for today\nsudo ausearch -ts today -i\nsudo aureport --summary -i\n\n# Validate rsyslog config${cfg().destination==='local'?' (not selected)':' and delivery'}\nsudo rsyslogd -N1\n`}
function tabData(){return {rules:{text:rulesText(),file:'auditcraft.rules'},rsyslog:{text:rsyslogText(),file:'60-auditcraft.conf'},install:{text:installText(),file:'install-auditcraft.sh'},verify:{text:verifyText(),file:'verify-auditcraft.sh'}}[currentTab]}
function warningText(){const r=rules(),c=cfg(),w=[];if(!r.length)w.push('Выберите хотя бы один пресет или добавьте свой путь.');if(r.some(x=>x[1].includes('r')))w.push('Аудит чтения может быстро увеличить объём журналов — используйте его точечно.');if(c.destination!=='local'&&!c.host)w.push('Укажите hostname или IP центрального log-сервера.');if(c.transport==='tcp'&&c.destination!=='local')w.push('TCP не шифрует события. Для production предпочтительнее TLS или изолированная сеть.');return w}
function render(){const r=rules();document.querySelectorAll('.preset').forEach(x=>{const on=active.has(x.dataset.id);x.classList.toggle('active',on);x.setAttribute('aria-pressed',on)});$('#hero-count').textContent=String(r.length).padStart(2,'0');$('#custom-list').innerHTML=custom.map((x,i)=>`<div class="custom-row"><code>${esc(x[0])}</code><span>-${esc(x[1])}</span><small>${esc(x[2])}</small><button type="button" data-remove="${i}">×</button></div>`).join('');const w=warningText();$('#warnings').innerHTML=w.length?`<b>ПРОВЕРЬТЕ ПЕРЕД DEPLOY</b>${w.map(x=>`<span>${esc(x)}</span>`).join('')}`:'<b class="ok">✓ CONFIGURATION LOOKS GOOD</b><span>Пути всё равно нужно проверить на целевой машине.</span>';const d=tabData();code.textContent=d.text;$('#download-button').textContent=`Скачать ${d.file} ↓`;$('#explain-list').innerHTML=active.size?[...active].map(id=>{const p=presets.find(x=>x[0]===id);return `<div><b>${p[2]}</b><span>${p[3]}</span></div>`}).join(''):'<p class="empty">Выберите пресеты — здесь появится объяснение набора аудита.</p>';localStorage.setItem('auditcraft-config',JSON.stringify(state()))}
function state(){return {active:[...active],custom,cfg:cfg()}}
function applyState(s){active.clear();(s.active||[]).forEach(x=>active.add(x));custom=Array.isArray(s.custom)?s.custom:[];if(s.cfg)Object.entries(s.cfg).forEach(([k,v])=>{const e=$('#'+({host:'log-host',port:'log-port'}[k]||k));if(e)e.value=v});render()}
presets.forEach(p=>{const b=document.createElement('button');b.type='button';b.className='preset';b.dataset.id=p[0];b.innerHTML=`<span class="preset-title"><i>${p[1]}</i><strong>${p[2]}</strong><em>✓</em></span><small>${p[3]}</small>`;b.addEventListener('click',()=>{active.has(p[0])?active.delete(p[0]):active.add(p[0]);render()});grid.append(b)});
Object.entries(profileNames).forEach(([id,name])=>{const b=document.createElement('button');b.type='button';b.textContent=name;b.addEventListener('click',()=>{active.clear();profileMap[id].forEach(x=>active.add(x));render();b.classList.add('picked');setTimeout(()=>b.classList.remove('picked'),500)});profiles.append(b)});
$('#path-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget),path=d.get('path').trim(),perms=d.getAll('permission').join(''),key=d.get('key').trim().replace(/\s+/g,'_')||'custom_path';if(!path.startsWith('/'))return alert('Укажите абсолютный путь, начинающийся с /.');if(!perms)return alert('Выберите хотя бы одно событие.');custom.push([path,perms,key]);e.currentTarget.reset();e.currentTarget.querySelector('[value="w"]').checked=true;e.currentTarget.querySelector('[value="a"]').checked=true;render()});
$('#custom-list').addEventListener('click',e=>{if(e.target.dataset.remove!==undefined){custom.splice(+e.target.dataset.remove,1);render()}});$('#clear-all').onclick=()=>{active.clear();custom=[];render()};document.querySelectorAll('#distro,#destination,#log-host,#log-port,#transport').forEach(x=>x.addEventListener('input',render));document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>{currentTab=x.dataset.tab;document.querySelectorAll('.tab').forEach(y=>y.classList.toggle('active',y===x));render()});
$('#copy-button').onclick=async()=>{const value=code.textContent;try{await navigator.clipboard.writeText(value)}catch{const t=document.createElement('textarea');t.value=value;document.body.append(t);t.select();document.execCommand('copy');t.remove()}$('#copy-button').textContent='✓ Скопировано';setTimeout(()=>$('#copy-button').textContent='⧉ Копировать',1300)};$('#download-button').onclick=()=>{const d=tabData(),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([d.text],{type:'text/plain'}));a.download=d.file;a.click();URL.revokeObjectURL(a.href)};
$('#save-config').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state(),null,2)],{type:'application/json'}));a.download='auditcraft-config.json';a.click();URL.revokeObjectURL(a.href)};$('#share-config').onclick=async()=>{const v=btoa(unescape(encodeURIComponent(JSON.stringify(state()))));const url=`${location.origin}${location.pathname}#config=${v}`;try{await navigator.clipboard.writeText(url);$('#share-config').textContent='✓ Ссылка скопирована'}catch{prompt('Скопируйте ссылку:',url)}setTimeout(()=>$('#share-config').textContent='Скопировать ссылку',1500)};$('#load-demo').onclick=()=>applyState({active:profileMap.web,custom:[['/opt/example-app','wa','example_app']],cfg:{distro:'debian',destination:'rsyslog',host:'logs.example.com',port:'6514',transport:'tls'}});
try{const hash=location.hash.match(/^#config=(.+)$/);if(hash)applyState(JSON.parse(decodeURIComponent(escape(atob(hash[1])))));else{const saved=localStorage.getItem('auditcraft-config');if(saved)applyState(JSON.parse(saved))}}catch{}$('#year').textContent=new Date().getFullYear();render();
