const presets = [
  { id:'auth', icon:'⌁', title:'SSH и авторизация', text:'sshd_config, ключи, sudoers и события входа', rules:[['/etc/ssh/sshd_config','wa','ssh_config'],['/etc/ssh/sshd_config.d','wa','ssh_config'],['/etc/sudoers','wa','sudoers'],['/etc/sudoers.d','wa','sudoers'],['/var/log/auth.log','wa','auth_log']] },
  { id:'identity', icon:'◉', title:'Учётные записи', text:'Пользователи, группы, пароли и shadow', rules:[['/etc/passwd','wa','identity'],['/etc/group','wa','identity'],['/etc/shadow','wa','identity'],['/etc/gshadow','wa','identity'],['/etc/security/opasswd','wa','identity']] },
  { id:'system', icon:'⚙', title:'Система и службы', text:'systemd, загрузчик, модули и hostname', rules:[['/etc/systemd/system','wa','systemd'],['/usr/lib/systemd/system','wa','systemd'],['/etc/hostname','wa','system_config'],['/etc/hosts','wa','system_config'],['/etc/modprobe.d','wa','kernel_modules']] },
  { id:'schedule', icon:'◷', title:'Cron и задачи', text:'Планировщики cron, at и системные таймеры', rules:[['/etc/crontab','wa','cron'],['/etc/cron.d','wa','cron'],['/etc/cron.daily','wa','cron'],['/var/spool/cron','wa','cron'],['/etc/at.allow','wa','at_jobs']] },
  { id:'network', icon:'↔', title:'Сеть', text:'Конфигурация интерфейсов, DNS и firewall', rules:[['/etc/hosts','wa','network_config'],['/etc/resolv.conf','wa','network_config'],['/etc/network','wa','network_config'],['/etc/NetworkManager','wa','network_config'],['/etc/nftables.conf','wa','firewall']] },
  { id:'privilege', icon:'◆', title:'Привилегии', text:'Бинарные файлы, suid/sgid и sudo', rules:[['/usr/bin/sudo','x','privileged'],['/usr/bin/su','x','privileged'],['/bin/su','x','privileged'],['/etc/sudo.conf','wa','sudoers']] },
  { id:'logs', icon:'▤', title:'Логи auditd', text:'Настройки демона и сохранность журналов', rules:[['/etc/audit/auditd.conf','wa','audit_config'],['/etc/audit/rules.d','wa','audit_rules'],['/var/log/audit','wa','audit_log']] },
  { id:'containers', icon:'□', title:'Контейнеры', text:'Docker и container runtime конфигурация', rules:[['/etc/docker','wa','docker'],['/etc/containerd','wa','containerd'],['/etc/containers','wa','containers']] }
];
const active = new Set(); let custom = [];
const grid = document.querySelector('#preset-grid'), output = document.querySelector('#rules-output'), count = document.querySelector('#rule-count'), download = document.querySelector('#download-button');
function esc(v){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function allRules(){return [...presets.filter(p=>active.has(p.id)).flatMap(p=>p.rules),...custom]}
function render(){const rules=allRules(); document.querySelectorAll('.preset').forEach(el=>{const enabled=active.has(el.dataset.id);el.classList.toggle('active',enabled);el.setAttribute('aria-pressed',enabled)}); document.querySelector('#custom-list').innerHTML=custom.map((r,i)=>`<div class="custom-rule"><code>${esc(r[0])}</code><span class="permission-badge">-${esc(r[1])}</span><span class="key-badge">${esc(r[2])}</span><button class="remove" data-index="${i}" type="button" aria-label="Удалить путь ${esc(r[0])}">×</button></div>`).join(''); const content=rules.length ? `# AuditCraft — generated auditd rules\n# Review paths before deploying to production.\n\n${rules.map(([path,perm,key])=>`-w ${path} -p ${perm} -k ${key || 'auditcraft'}`).join('\n')}\n` : '# Выберите пресеты слева,\n# чтобы начать сборку правил.'; output.querySelector('code').textContent=content; count.textContent=`${rules.length} ${rules.length===1?'RULE':'RULES'}`; download.disabled=!rules.length}
presets.forEach(p=>{const el=document.createElement('button');el.type='button';el.className='preset';el.dataset.id=p.id;el.setAttribute('aria-pressed','false');el.innerHTML=`<span class="preset-title"><span class="preset-icon">${p.icon}</span><span>${p.title}</span><span class="check">✓</span></span><p>${p.text}</p>`;el.addEventListener('click',()=>{active.has(p.id)?active.delete(p.id):active.add(p.id);render()});grid.append(el)});
document.querySelector('#path-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget),path=data.get('path').trim(),perm=data.getAll('permission').join(''),key=data.get('key').trim().replace(/\s+/g,'_');if(!path)return document.querySelector('#custom-path').focus();if(!path.startsWith('/'))return alert('Укажите абсолютный путь, начинающийся с /.');if(!perm)return alert('Выберите хотя бы одно событие.');custom.push([path,perm,key||'custom_path']);e.currentTarget.reset();e.currentTarget.querySelector('[value="w"]').checked=true;e.currentTarget.querySelector('[value="a"]').checked=true;render()});
document.querySelector('#custom-list').addEventListener('click',e=>{if(e.target.matches('.remove')){custom.splice(Number(e.target.dataset.index),1);render()}});
document.querySelector('#clear-all').addEventListener('click',()=>{active.clear();custom=[];render()});
document.querySelector('#copy-button').addEventListener('click',async e=>{if(!allRules().length)return;const value=output.querySelector('code').textContent;try{await navigator.clipboard.writeText(value)}catch{const area=document.createElement('textarea');area.value=value;document.body.append(area);area.select();document.execCommand('copy');area.remove()}e.currentTarget.textContent='✓ Скопировано';setTimeout(()=>e.currentTarget.textContent='⧉ Копировать',1400)});
download.addEventListener('click',()=>{const blob=new Blob([output.querySelector('code').textContent],{type:'text/plain'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='auditcraft.rules';link.click();URL.revokeObjectURL(link.href)});document.querySelector('#year').textContent=new Date().getFullYear();render();
